branches:
  drag-and-drop-books:
    enabled: true
  librarian-rolling:
    enabled: true
  fletcher-rolling:
    enabled: true
  villager-acceleration:
    enabled: true
    growth-speed-multiplier: 5.0
    curing-speed-multiplier: 5.0
    breeding-cooldown-seconds: 60
